export const SVELTE_WHEEL_API_KEY = '';
export const PUBLIC_FIREBASE_API_KEY = '';
export const PUBLIC_FIREBASE_AUTH_DOMAIN = '';
export const PUBLIC_FIREBASE_PROJECT_ID = '';
export const PUBLIC_FIREBASE_STORAGE_BUCKET = '';
export const PUBLIC_FIREBASE_MESSAGING_SENDER_ID = '';
export const PUBLIC_FIREBASE_APP_ID = '';
export const PUBLIC_FIREBASE_MEASUREMENT_ID = '';
