const SVELTE_WHEEL_API_KEY = ''
const PUBLIC_FIREBASE_API_KEY = ''
const PUBLIC_FIREBASE_AUTH_DOMAIN = ''
const PUBLIC_FIREBASE_PROJECT_ID = ''
const PUBLIC_FIREBASE_STORAGE_BUCKET = ''
const PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ''
const PUBLIC_FIREBASE_APP_ID = ''
const PUBLIC_FIREBASE_MEASUREMENT_ID = ''

export {
  SVELTE_WHEEL_API_KEY, PUBLIC_FIREBASE_API_KEY, PUBLIC_FIREBASE_AUTH_DOMAIN,
  PUBLIC_FIREBASE_PROJECT_ID, PUBLIC_FIREBASE_STORAGE_BUCKET,
  PUBLIC_FIREBASE_MESSAGING_SENDER_ID, PUBLIC_FIREBASE_APP_ID,
  PUBLIC_FIREBASE_MEASUREMENT_ID
}
